/*
 * This source file was generated by the Gradle 'init' task
 */
package parcial;

import java.util.Scanner;

public class App {

    
    
    
    public static void main(String[] args) {
        try{
            //Datos de entrada 
           String decadaDeVehiculo = "";
           int avalouVehiculo = 0;
    
           //Datos de salida 
           double resultadoRodamiento = 0;
           double resultadoSeguro = 0;
           double resultadoTotalImpuestos = 0;

           //Scanner create

           Scanner Bitas = new Scanner(System.in);

           //Decada del vehiculo

           System.out.println("Ingerese la decada del vehiculo: ");
           decadaDeVehiculo = Bitas.nextLine();

           //avaluo del vehiculo

           System.out.println("Ingrese el avaluo del vehiculo: ");
           avalouVehiculo = Bitas.nextInt();
           Bitas.nextLine();


           //Funcion Resultado de rodamiento

           resultadoRodamiento = calcularLaTasaDeRodamiento(decadaDeVehiculo, avalouVehiculo);

           //Funcion Resultado de seguro

           resultadoSeguro = calcularLaTasaDeRodamiento(decadaDeVehiculo, avalouVehiculo);
           

           //pago total
           resultadoTotalImpuestos = resultadoRodamiento + resultadoSeguro;

           System.out.println("El vehiculo tiene un avaluo de " + avalouVehiculo + ", Impuesto de rodamiento de" + resultadoRodamiento + ", valor de la tasa de seguro" + resultadoSeguro +", Total a pagar" + resultadoTotalImpuestos);
           
        
        }catch(Exception e){

        }
        }
        
        //Primera funcion
    
        public static double calcularLaTasaDeRodamiento(String decada, int avaluo){
        try {
            //variable

            double precioConTasaDeRodamiento = 0;

            //condicionales
            if (decada.equals("90")) {
                precioConTasaDeRodamiento = avaluo * 0.0409;
                
            }
            else if (decada.equals("00")){
                precioConTasaDeRodamiento = avaluo * 0.0434;
            }
            else if (decada.equals("10")) {
                precioConTasaDeRodamiento = avaluo * 0.0493;
                
            }
            else if (decada.equals("20")) {
                precioConTasaDeRodamiento = avaluo * 0.5680;
                
            }
            else{
                precioConTasaDeRodamiento = -1;
            }
            return precioConTasaDeRodamiento;
        }catch (Exception e){
                return -1;
            }
    

        }
    
    

    //segunda funcion

    
    public static double calcularTasaDeSeguro(String decada, int avaluo ){
        try {
            ///variables
            double precioConTasaDeSeguro = 0;

            ///Condicionales 
            if(decada.equals("90")){
                precioConTasaDeSeguro = avaluo * 0.00816;
            }
            else if(decada.equals("00")){
                precioConTasaDeSeguro = avaluo * 0.00798;
            }
            else if(decada.equals("10")){
                precioConTasaDeSeguro = avaluo * 0.00712;
            }
            else if(decada.equals("20")){
                precioConTasaDeSeguro = avaluo * 0.00699;
            }
            else{
                precioConTasaDeSeguro =-1;
            }

            return precioConTasaDeSeguro;

        } catch (Exception e) {
            return -1;
        }

    }

    
}

       



            
        
    

